version: "3.8"

services:
  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    # volumes:
    #   - qdrant_storage:/qdrant/storage

# volumes:
#   qdrant_storage:
#     driver: local